import { BadgePercent, Bolt, ChevronsUpDown, ClipboardX, LogOut, } from "lucide-react";
import { Avatar, AvatarFallback, AvatarImage, } from "./ui/avatar";
import { DropdownMenu, DropdownMenuContent, DropdownMenuGroup, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger, } from "./ui/dropdown-menu";
import { SidebarMenu, SidebarMenuButton, SidebarMenuItem, useSidebar, } from "./ui/sidebar";
import * as React from "react";
export function NavUser({ user, }) {
    const { isMobile } = useSidebar();
    return (React.createElement(SidebarMenu, null,
        React.createElement(SidebarMenuItem, null,
            React.createElement(DropdownMenu, null,
                React.createElement(DropdownMenuTrigger, { asChild: true },
                    React.createElement(SidebarMenuButton, { size: "lg", className: " data-[state=open]:bg-gray-100 data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground" },
                        React.createElement(Avatar, { className: "h-8 w-8 rounded-lg" },
                            React.createElement(AvatarImage, { src: user.avatar, alt: user.name }),
                            React.createElement(AvatarFallback, { className: "rounded-lg" }, "CN")),
                        React.createElement("div", { className: "grid flex-1 text-left text-sm leading-tight" },
                            React.createElement("span", { className: "truncate font-semibold" }, user.name),
                            React.createElement("span", { className: "truncate text-xs" }, user.email)),
                        React.createElement(ChevronsUpDown, { className: "ml-auto size-4" }))),
                React.createElement(DropdownMenuContent, { className: "w-[--radix-dropdown-menu-trigger-width] min-w-[330px] rounded-lg", side: isMobile ? "bottom" : "right", align: "end", sideOffset: 4 },
                    React.createElement(DropdownMenuLabel, { className: "p-0 font-normal" },
                        React.createElement("div", { className: "flex items-center gap-2 px-1 py-1.5 text-left text-sm" },
                            React.createElement(Avatar, { className: "h-8 w-8 rounded-lg" },
                                React.createElement(AvatarImage, { src: user.avatar, alt: user.name }),
                                React.createElement(AvatarFallback, { className: "rounded-lg" }, "CN")),
                            React.createElement("div", { className: "grid flex-1 text-left text-sm leading-tight" },
                                React.createElement("span", { className: "truncate font-semibold" }, user.name),
                                React.createElement("span", { className: "truncate text-xs" }, user.email)))),
                    React.createElement(DropdownMenuSeparator, null),
                    React.createElement(DropdownMenuGroup, { className: "grid grid-cols-2 w-full" },
                        React.createElement(DropdownMenuItem, null,
                            React.createElement("div", { className: "flex items-center gap-1" },
                                React.createElement(Bolt, { size: 18 }),
                                "Roles ",
                                React.createElement("span", null, "8"))),
                        React.createElement(DropdownMenuItem, null,
                            React.createElement("div", { className: "flex items-center gap-1" },
                                React.createElement(ClipboardX, { size: 18 }),
                                "Cards ",
                                React.createElement("span", null, "5")))),
                    React.createElement(DropdownMenuGroup, { className: "grid grid-cols-2 w-full" }),
                    React.createElement(DropdownMenuSeparator, null),
                    React.createElement(DropdownMenuGroup, { className: "grid grid-cols-2  " },
                        React.createElement(DropdownMenuItem, null,
                            "56 ",
                            React.createElement("span", null, "Squad Members")),
                        React.createElement(DropdownMenuItem, null,
                            "10 ",
                            React.createElement("span", null, "Mini Leader")),
                        React.createElement(DropdownMenuItem, null,
                            "4 ",
                            React.createElement("span", null, "Groups")),
                        React.createElement(DropdownMenuItem, null,
                            "5 ",
                            React.createElement("span", null, "Mini Member"))),
                    React.createElement(DropdownMenuSeparator, null),
                    React.createElement(DropdownMenuItem, null,
                        React.createElement(BadgePercent, null),
                        React.createElement("span", null, "salary")),
                    React.createElement(DropdownMenuGroup, null,
                        React.createElement(DropdownMenuItem, null,
                            React.createElement(LogOut, null),
                            "Log out")))))));
}
